added additional checks

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -5,9 +5,17 @@ on:
  workflow_dispatch:
    inputs:
      environment:
-        description: Specify the environment(dev or prod)
+        type: choice
+        description: "Specify the environment(dev or prod)"
+        options:
+          - dev
+          - prod
         required: true
         default: 'dev'
+      
+     tag:
+      description: "Specify the image tag to be pulled for prod"
+      required: false
 
 env:
  var1: This is workflow level env var accessible in the entire workflow
@@ -26,16 +34,30 @@ jobs:
             uses: actions/checkout@v4 
             env:
              var3: This is step level env var accessible only in this step  
+        
+
+          - name: Validate PROD inputs
+            run: |
+             if [[ "${{ github.event.inputs.environment }}" == "prod" && -z "${{ github.event.inputs.tag }}" ]]; then
+             echo "ERROR: tag is required for PROD deployments"
+             exit 1
+             fi
+          
+          - name: Set conditional env
+            run: |
+             if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
+             echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
+             fi
 
           - name: Access env variables
             run: |
               # env.var3 will be empty because its set at step level
               echo "${{env.var1}}" "${{env.var2}}" "${{env.var3}}" "${{env.tag}}"
-              ls -al docker/
               echo "${{github.event.inputs.environment}}"
                         
 
           - name: Login to DockerHub
+            if: ${{ github.event.inputs.environment == 'dev' }}
             uses: docker/login-action@v3
             with:
               username: ${{vars.DOCKERHUB_USERNAME}}
@@ -44,6 +66,7 @@ jobs:
 
 
           - name: Build Docker image
+            if: ${{ github.event.inputs.environment == 'dev' }}
             uses: docker/build-push-action@v5
             with:
               push: true  # so that image is pushed to Dockerhub as well
@@ -53,11 +76,7 @@ jobs:
           
           - name: Run using compose
             run: |
-              ls -al docker/
-              echo "${{github.event.inputs.environment}}"
               docker compose -p cart-microservices-${{github.event.inputs.environment}} -f docker/docker-compose.yml -f docker/docker-compose.${{github.event.inputs.environment}}.override.yml up -d --remove-orphans --no-build
-              # docker image prune --force
-              # docker compose ps
-
+              
             
 
